CREATE DATABASE manyusers;
USE manyusers;
CHANGE MASTER TO MASTER_HOST='mysql-m', MASTER_USER='slave2', MASTER_PASSWORD='password',
MASTER_LOG_FILE = 'mysql-bin.000003', MASTER_LOG_POS = 604;
START SLAVE;